replicacount: 1

image:
  repository: kopilb/go-web-app
  pullPolicy: IfNotPresent
  tag: "10512932693"

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths: 
        - path: /
          pathType: ImplementationSpecific